/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 23 15:39:58 GMT 2018
 */

package com.merqury.phoebe.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.util.LogTrace;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LogTrace_ESTest extends LogTrace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LogTrace.Log("mRn", "6Gawl&P?", "", "B|2", "JzJKziW4p");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LogTrace logTrace0 = new LogTrace();
  }
}
