/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 26 21:06:23 GMT 2018
 */

package com.merqury.phoebe.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.merqury.phoebe.beans.NoteTypeFacade;
import com.merqury.phoebe.controller.NoteTypeController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractController_ESTest extends AbstractController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoteTypeFacade noteTypeFacade0 = mock(NoteTypeFacade.class, new ViolatedAssumptionAnswer());
      NoteTypeController noteTypeController0 = null;
      try {
        noteTypeController0 = new NoteTypeController();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.merqury.phoebe.controller.AbstractController", e);
      }
  }
}
