/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:49:33 GMT 2018
 */

package com.merqury.phoebe.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.controller.UserLoginHistoryController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserLoginHistoryController_ESTest extends UserLoginHistoryController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserLoginHistoryController userLoginHistoryController0 = new UserLoginHistoryController();
  }
}
