/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Feb 26 20:56:29 GMT 2018
 */

package com.merqury.phoebe.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class JsfUtil_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.merqury.phoebe.util.JsfUtil"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JsfUtil_ESTest_scaffolding.class.getClassLoader() ,
      "org.primefaces.event.data.PostPageEvent",
      "org.primefaces.component.timeline.DefaultTimelineUpdater",
      "org.primefaces.component.lifecycle.PhaseInfo",
      "org.primefaces.event.CaptureEvent",
      "org.primefaces.model.timeline.TimelineEvent",
      "org.primefaces.visit.ResetInputVisitCallback",
      "org.primefaces.config.StartupPrimeConfiguration",
      "org.primefaces.webapp.PostConstructApplicationEventListener",
      "org.primefaces.model.NativeUploadedFile",
      "org.primefaces.event.data.PostFilterEvent",
      "org.primefaces.application.resource.DynamicResourcesPhaseListener",
      "org.primefaces.model.UploadedFile",
      "org.primefaces.component.lifecycle.LifecyclePhaseListener",
      "org.primefaces.config.PrimeConfiguration",
      "org.primefaces.event.AutoCompleteEvent",
      "org.primefaces.event.data.PostSortEvent",
      "org.primefaces.component.timeline.TimelineUpdater",
      "org.primefaces.event.FileUploadEvent",
      "com.merqury.phoebe.util.JsfUtil",
      "org.primefaces.event.FlowEvent"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JsfUtil_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.primefaces.event.FlowEvent",
      "org.primefaces.event.AutoCompleteEvent",
      "org.primefaces.event.data.PostFilterEvent",
      "org.primefaces.visit.ResetInputVisitCallback",
      "org.primefaces.event.data.PostPageEvent",
      "org.primefaces.event.data.PostSortEvent",
      "org.primefaces.event.CaptureEvent",
      "org.primefaces.model.NativeUploadedFile",
      "org.primefaces.event.FileUploadEvent",
      "org.primefaces.component.lifecycle.LifecyclePhaseListener",
      "org.primefaces.webapp.PostConstructApplicationEventListener",
      "org.primefaces.application.resource.DynamicResourcesPhaseListener",
      "org.primefaces.component.timeline.DefaultTimelineUpdater"
    );
  }
}
