/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:56:17 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.NoteFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoteFacade_ESTest extends NoteFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoteFacade noteFacade0 = new NoteFacade();
      Injector.injectEntityManager(noteFacade0, (Class<?>) NoteFacade.class);
      Injector.validateBean(noteFacade0, (Class<?>) NoteFacade.class);
      EntityManager entityManager0 = noteFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
