/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:57:23 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.NoteTypeFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoteTypeFacade_ESTest extends NoteTypeFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoteTypeFacade noteTypeFacade0 = new NoteTypeFacade();
      Injector.injectEntityManager(noteTypeFacade0, (Class<?>) NoteTypeFacade.class);
      Injector.validateBean(noteTypeFacade0, (Class<?>) NoteTypeFacade.class);
      EntityManager entityManager0 = noteTypeFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
