/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:51:54 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.OrgParamFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrgParamFacade_ESTest extends OrgParamFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrgParamFacade orgParamFacade0 = new OrgParamFacade();
      Injector.injectEntityManager(orgParamFacade0, (Class<?>) OrgParamFacade.class);
      Injector.validateBean(orgParamFacade0, (Class<?>) OrgParamFacade.class);
      EntityManager entityManager0 = orgParamFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
