/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:59:34 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.PermissionsFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PermissionsFacade_ESTest extends PermissionsFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PermissionsFacade permissionsFacade0 = new PermissionsFacade();
      Injector.injectEntityManager(permissionsFacade0, (Class<?>) PermissionsFacade.class);
      Injector.validateBean(permissionsFacade0, (Class<?>) PermissionsFacade.class);
      EntityManager entityManager0 = permissionsFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
