/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:58:28 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.PersonFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PersonFacade_ESTest extends PersonFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PersonFacade personFacade0 = new PersonFacade();
      Injector.injectEntityManager(personFacade0, (Class<?>) PersonFacade.class);
      Injector.validateBean(personFacade0, (Class<?>) PersonFacade.class);
      EntityManager entityManager0 = personFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
