/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 19:02:56 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.PrayerRequestFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrayerRequestFacade_ESTest extends PrayerRequestFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrayerRequestFacade prayerRequestFacade0 = new PrayerRequestFacade();
      Injector.injectEntityManager(prayerRequestFacade0, (Class<?>) PrayerRequestFacade.class);
      Injector.validateBean(prayerRequestFacade0, (Class<?>) PrayerRequestFacade.class);
      EntityManager entityManager0 = prayerRequestFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
