/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:52:59 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.PrayerRequestNatureFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrayerRequestNatureFacade_ESTest extends PrayerRequestNatureFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PrayerRequestNatureFacade prayerRequestNatureFacade0 = new PrayerRequestNatureFacade();
      Injector.injectEntityManager(prayerRequestNatureFacade0, (Class<?>) PrayerRequestNatureFacade.class);
      Injector.validateBean(prayerRequestNatureFacade0, (Class<?>) PrayerRequestNatureFacade.class);
      EntityManager entityManager0 = prayerRequestNatureFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
