/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 18:54:05 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.RolesFacade;
import com.merqury.phoebe.entity.Permissions;
import java.util.List;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RolesFacade_ESTest extends RolesFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RolesFacade rolesFacade0 = new RolesFacade();
      Injector.injectEntityManager(rolesFacade0, (Class<?>) RolesFacade.class);
      Injector.validateBean(rolesFacade0, (Class<?>) RolesFacade.class);
      List<Permissions> list0 = rolesFacade0.listOfPermissionsInRole((Integer) null);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RolesFacade rolesFacade0 = new RolesFacade();
      Injector.injectEntityManager(rolesFacade0, (Class<?>) RolesFacade.class);
      Injector.validateBean(rolesFacade0, (Class<?>) RolesFacade.class);
      EntityManager entityManager0 = rolesFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
