/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 21 19:04:01 GMT 2018
 */

package com.merqury.phoebe.beans;

import org.junit.Test;
import static org.junit.Assert.*;
import com.merqury.phoebe.beans.UserLoginHistoryFacade;
import javax.persistence.EntityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserLoginHistoryFacade_ESTest extends UserLoginHistoryFacade_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserLoginHistoryFacade userLoginHistoryFacade0 = new UserLoginHistoryFacade();
      Injector.injectEntityManager(userLoginHistoryFacade0, (Class<?>) UserLoginHistoryFacade.class);
      Injector.validateBean(userLoginHistoryFacade0, (Class<?>) UserLoginHistoryFacade.class);
      EntityManager entityManager0 = userLoginHistoryFacade0.getEntityManager();
      assertNotNull(entityManager0);
  }
}
